# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

gems:
  - jekyll-feed

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "Gemfile", "Gemfile.lock"] # files to exclude
excerpt_separator: "\n<!-- excerpt -->\n"

markdown: kramdown
highlighter: pygments
#markdown: redcarpet
#highlighter: pygments

title: Adam.Blog()
description: Adam Presley's blog
author: Adam Presley
email: adam@adampresley.com
author_image: /assets/adampresley/images/adam-bowtie.jpg
twitter_handle: "@adampresley"

logo: /assets/adampresley/images/adam-bowtie.jpg
cover: /assets/images/code-background-screenshot.png
rss_path: feed.xml
categories_path:
tags_path: tags.html

BASE_PATH:

social:
  - icon: twitter
    url:  https://twitter.com/adampresley
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url:  https://github.com/adampresley
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:  google-plus
    url: https://plus.google.com/+AdamPresley/posts
    desc:  Add me on google+
    share_url:
    share_title:
    share_link:
