BaseUrl= "http://adampresley.com/"
LanguageCode= "en-US"
Title= "Adam.Blog()"
paginate= 5
DisqusShortname= "adampresleyblog"
Copyright= "Adam Presley. All rights reserved - 2016"
canonifyurls= true
pygmentsuseclasses=false

[params]
	description= "I'm bringin' nerdy back"
	cover = "assets/images/code-background-screenshot.png"
	author = "Adam Presley"
	authorlocation = "Texas, USA"
	authorwebsite = "http://adampresley.com"
	logo = "assets/adampresley/images/adam-bowtie.jpg"
	googleAnalyticsUserID = "UA-44927419-1"
	githubName = "adampresley"
	twitterName = "adampresley"

[permalinks]
	post= "/:year/:month/:day/:slug"